version: '3'
services:

  frontend:
    container_name: frontend
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: ./backend/.env

  swagger-editor:
    container_name: swagger-editor
    image: swaggerapi/swagger-editor
    ports:
      - 8000:8080

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger/openapi.yml:/openapi.yml
    ports:
      - 8001:8080
    environment:
      SWAGGER_JSON: /openapi.yml
