version: '3'
services:

  frontend:
    container_name: frontend
    build:
      context: ./docker
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: ./docker
      dockerfile: backend.Dockerfile
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - back-tier

  database:
    container_name: database
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=user42
      - POSTGRES_USER=user42
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
