version: '3'
services:

  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./docker/frontend.Dockerfile
      # volumes:
      # - ./frontend:/frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./docker/backend.Dockerfile
      # volumes:
      # - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
      - 5555:5555
    networks:
      - back-tier

  database:
    container_name: database
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    networks:
      - back-tier
    volumes:
      - db-vol:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
          "||",
          "exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 100

networks:
  back-tier:
    driver: bridge

volumes:
  db-vol:
