openapi: 3.0.0
info:
  version: 1.0.0
  title: ft_transcendence API
servers:
  - url: 'http://localhost:8001'
paths:
  /users:
    get:
      description: >
        get all users
      responses:
        '200':
          description: user response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: "object"
      required:
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
          enum:
            - 1
            - 2
            - 3
        name:
          type: "string"
          enum:
            - "User Taro"
            - "Test Umeko"
            - "Tanaka Tokyo"
        image:
          type: "string"
          description: "user logo"
          enum:
            - "https://pngimg.com/uploads/github/github_PNG80.png"
            - "https://velog.velcdn.com/images/exoluse/post/3a85680a-adcf-44f8-8b8e-bbf6c5ac7659/Nestjs.png"
            - "https://logodix.com/logo/1193669.png"
